### ISSUE TITLE
The example-code does not work on current astro versions

### ISSUE THREAD

**Issue by LoeschMaximilian** [pep108/astro-mithril#1]
I tried to recreate the example in a fresh astro project using `yarn create astro`
and got this error
![image](https://github.com/pep108/astro-mithril/assets/93034785/557215eb-2883-4b2a-bf00-2842fb8828ad)

The package.json:
```
{
  "name": "",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro check && astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/check": "^0.6.0",
    "astro": "^4.8.2",
    "astro-mithril": "^0.0.7",
    "typescript": "^5.4.5"
  }
}
```

**Comment by pep108** [comment]
I'll take a look and update the repo soon. Compatibility broke with Astro v4 and I haven't had time to update the project

**Comment by pep108** [comment]
with the updates from @YohYamasaki, this issue is now resolved.
